muypicky/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
    )


app_name = 'menus'
urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[\w-]+)/edit$', ItemUpdateView.as_view(), name='update')
]

muypicky/profiles/urls.py
from django.conf.urls import url


from .views import (
    ProfileDetailView
    )


app_name = 'profiles'
urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='details'),
]

muypicky/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import Restaurant


class Item(models.Model):
    # associations
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(Restaurant)
    # item stuff
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text='Separate each item by comma')
    excludes        = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

muypicky/menus/forms.py
from django import forms


from restaurants.models import Restaurant


from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]

    def __init__(self, user = None, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = Restaurant.objects.filter(owner=user)
        print(kwargs)
        print(user)

muypicky/menus/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import ItemForm
from .models import Item
# Create your views here.


class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'home.html', {})

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs = Item.objects.filter(user__id__in = is_following_user_ids, public=True).order_by("-updated")
        context = {'object_list':qs}
        return render(request, 'menus/home_feed.html', context)

class ItemListView( LoginRequiredMixin, ListView):
    login_url = '/login/'

    def get_queryset(self):
        return Item.objects.filter(user = self.request.user)


class ItemDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'

    def get_queryset(self, **kwargs):
        return Item.objects.filter(user = self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
    form_class = ItemForm
    template_name = 'form.html'
    login_url = '/login/'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_queryset(self):
        return Item.objects.filter(user = self.request.user)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self,*args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args,**kwargs)
        context['title'] = 'Create Item'
        return context



class ItemUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    form_class = ItemForm
    template_name = 'form.html'

    def get_queryset(self):
        return Item.objects.filter(user = self.request.user)

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
        return kwargs

    def get_context_data(self,*args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args,**kwargs)
        context['title'] = 'Update Item'
        return context

muypicky/menus/templates/menus/home_feed.html
{% extends 'base.html' %}


{% block content %}



<ul>
{% for obj in object_list %}

    <div class='row'>
    <div class='col-sm-12'>
        <div class='thumbnail' style='margin-bottom: 15px;  text-align: left;'>
            <h4><b><a href="{% url 'profiles:details' username=obj.user.username%}">{{ obj.user.username }}</a></b></h4>
            <h5>{{ obj.name }}</h5>
            {{ obj.restaurant.title }} | {{ obj.restaurant.location }} | {{ obj.restaurant.category}}
<ul>

                        {% for ing in obj.get_contents %}
                            {{ ing}}
                        {% endfor %}

</ul>
        </div>
    </div>
    </div>


    </li>
    {% empty %}
    <li><a href='{% url "menus:create" %}'>Add Menu Item</a></li>
{% endfor %}
</ul>
{% endblock %}

muypicky/menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>
{% if object.contents %}
Contents
<ul>    
    {% for item in object.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
{% endif %}

 {% if object.excludes %}
Excludes
<ul>    
    {% for item in object.get_excludes %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
    <a href='{% url "menus:update" pk=object.pk %}'>edit</a>
</div>
</div>
{% endif %}



{% endblock %}

muypicky/menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>Menu Items </h1>

<ul>
{% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
        {% if obj.contents %}
        Contents
        <ul>    
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}

         {% if obj.excludes %}
        Excludes
        <ul>    
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}


    </li>
    {% empty %}
    <li><a href='{% url "menus:create" %}'>Add Menu Item</a></li>
</ul>
</div>
</div>
{% endfor %}
</ul>
{% endblock %}